name: ci 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install poetry
      - run: poetry self add poetry-plugin-export
      - run: python -m poetry export -f requirements.txt --output requirements.txt --without-hashes 
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force